name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache-dependency-path: ""

    - name: 安装依赖
      run: pip install feedparser requests python-dateutil

    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py

    - name: 提交变更
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "更新游戏版本状态 [skip ci]"
          git pull --rebase
          git push
        fi
