name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # 步骤1：检出代码（不保留历史）
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # 仅拉取最新提交

    # 步骤2：使用GitHub缓存存储状态（关键创新点）
    - name: 恢复状态
      id: restore-state
      uses: actions/cache@v3
      with:
        path: last_known_versions.json
        key: steam-versions-${{ hashFiles('apps_to_monitor.json') }}

    # 步骤3：初始化状态文件
    - name: 初始化
      run: |
        if [ ! -f last_known_versions.json ]; then
          echo "{}" > last_known_versions.json
        fi

    # 步骤4：设置环境
    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 步骤5：运行监控
    - name: 执行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py

    # 步骤6：保存状态到缓存
    - name: 保存状态
      uses: actions/cache@v3
      with:
        path: last_known_versions.json
        key: steam-versions-${{ hashFiles('apps_to_monitor.json') }}
        restore-keys: |
          steam-versions-
