name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时检查一次（UTC时间）
  workflow_dispatch:        # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限

    steps:
    # 步骤1：检出代码
    - name: 检出仓库
      uses: actions/checkout@v4

    # 步骤2：设置Python环境
    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 步骤3：安装依赖（带验证）
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil
        echo "验证安装："
        pip show feedparser requests python-dateutil

    # 步骤4：初始化状态文件
    - name: 初始化状态
      run: |
        if [ ! -f last_known_versions.json ]; then
          echo "{}" > last_known_versions.json
          echo "已初始化状态文件"
        else
          echo "状态文件已存在"
        fi

    # 步骤5：运行监控脚本
    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py

    # 步骤6：保存状态（使用缓存）
    - name: 缓存状态
      uses: actions/cache@v3
      with:
        path: last_known_versions.json
        key: steam-versions-${{ hashFiles('apps_to_monitor.json') }}
