name: Steam游戏更新监控

on:
  schedule:
    # 每6小时运行一次（UTC时间）
    - cron: '0 */4 * * *'  # 关键修改处：将 */12 改为 */6
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil pytz
        echo "验证安装："
        pip show feedparser requests pytz

    - name: 恢复状态缓存
      uses: actions/cache@v3
      id: state-cache
      with:
        path: last_known_versions.json
        key: steam-state-${{ github.sha }}
        restore-keys: |
          steam-state-

    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py

    - name: 保存缓存
      uses: actions/cache/save@v3
      with:
        path: last_known_versions.json
        key: ${{ steps.state-cache.outputs.cache-primary-key }}
