name: SteamDB Monitor
on:
  schedule:
    - cron: "*/30 * * * *"  # 每30分钟检查一次
  workflow_dispatch:        # 支持手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 恢复缓存（记录已推送的BuildID）
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: steamdb_cache.json
          key: steamdb-${{ hashFiles('games.json') }}
          restore-keys: steamdb-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python steamdb_notifier.py

      # 保存缓存（如果有新更新）
      - name: Save cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: steamdb_cache.json
          key: steamdb-${{ hashFiles('games.json') }}
