name: SteamDB Monitor
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 使用新的缓存恢复方式
      - name: Restore cache
        id: cache
        uses: actions/cache@v3
        with:
          path: steamdb_cache.json
          key: steamdb-${{ hashFiles('games.json') }}
          restore-keys: |
            steamdb-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python steamdb_notifier.py

      # 仅在缓存发生变化时保存
      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: steamdb_cache.json
          key: steamdb-${{ hashFiles('games.json') }}'games.json') }}
