name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 检出代码（全新状态）
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true  # 关键参数：确保全新检出

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: 安装依赖
      run: pip install feedparser requests python-dateutil

    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # 确保状态文件存在
        if [ ! -f last_known_versions.json ]; then
          echo "{}" > last_known_versions.json
        fi
        python steam_monitor.py

    - name: 提交变更（冲突安全处理）
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 强制同步远程
        git fetch origin
        git reset --hard origin/main
        
        # 添加变更
        git add .
        if ! git diff --cached --quiet; then
          # 创建新提交（覆盖历史）
          git commit -m "更新游戏版本状态 $(date +'%Y-%m-%d %H:%M') [skip ci]"
          
          # 强制推送（仅限版本文件）
          git push origin main --force
        fi
