name: Steam Updates Monitor

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次（UTC时间）
  workflow_dispatch:         # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码（包含完整提交历史）
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # 2. 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil
    
    # 4. 运行监控脚本
    - name: Run monitor script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py
    
    # 5. 提交并推送变更（完整解决方案）
    - name: Commit and push changes
      run: |
        # 配置Git用户
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 使用GitHub Token设置远程仓库认证
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
        # 拉取最新代码并rebase
        git pull --rebase origin main
        
        # 添加变更文件
        git add .
        
        # 检查是否有实际变更
        if ! git diff --cached --quiet; then
          # 提交变更
          git commit -m "Auto-update: game versions [skip ci]"
          
          # 推送变更（显示推送进度）
          git push --verbose origin main
        else
          echo "No changes to commit"
        fi
