name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil pytz

    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # 确保文件使用Unix换行符
        dos2unix steam_monitor.py
        python steam_monitor.py

    - name: 提交状态变更
      if: always()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add last_known_versions.json
        git commit -m "Update game monitoring state" || echo "No changes to commit"
        git push
