name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许提交更改

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录

    - name: 初始化状态文件
      run: |
        if [ ! -f "last_known_versions.json" ]; then
          echo "{}" > last_known_versions.json
          echo "已创建初始状态文件"
        else
          echo "状态文件已存在"
        fi
        echo "当前目录内容:"
        ls -la

    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil pytz
        echo "已安装依赖:"
        pip list

    - name: 运行监控脚本
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python steam_monitor.py
        echo "状态文件内容:"
        cat last_known_versions.json || echo "无状态文件"

    - name: 提交状态更新
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add last_known_versions.json
        git diff-index --quiet HEAD || git commit -m "更新游戏状态 [skip ci]"
        git push
