name: Steam Updates Monitor

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 必须添加这个权限
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install feedparser requests python-dateutil
        
    - name: Run monitor script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py
      
    - name: Commit and push changes
      run: |
        # 配置Git身份
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 强制同步远程分支
        git fetch origin main
        git reset --hard origin/main
        
        # 添加并提交变更
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Update game versions [skip ci]"
          git push origin main
        fi
