name: Mass SteamDB Monitor
on:
  schedule:
    - cron: "*/30 * * * *"  # 每30分钟运行一次
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3, 4]  # 5个分片
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install aiohttp feedparser python-telegram-bot tenacity

      - name: Run monitor shard
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          SHARD_ID: ${{ matrix.shard }}
          TOTAL_SHARDS: 5
        run: python optimized_monitor.py

      - name: Upload cache
        uses: actions/upload-artifact@v3
        with:
          name: shard-${{ matrix.shard }}-cache
          path: steamdb_cache.json
