- name: Commit and push changes
  run: |
    # 配置Git身份
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    
    # 重置本地分支到远程最新状态
    git fetch origin main
    git reset --hard origin/main
    
    # 添加并强制推送
    git add .
    if ! git diff --cached --quiet; then
      git commit -m "Update: Game versions [skip ci]"
      git push origin main --force-with-lease
    fi
