name: Steam Updates Monitor

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次（UTC时间）
  workflow_dispatch:         # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用GITHUB_TOKEN认证
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil
        
    - name: Run monitor script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Update last known versions [skip ci]"
          git push
        fi
