name: Steam游戏更新监控

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次（UTC时间）
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许提交状态文件变更

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 初始化状态文件
      run: |
        if [ ! -f "last_known_versions.json" ]; then
          echo "初始化状态文件..."
          echo "{}" > last_known_versions.json
        fi

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests python-dateutil pytz

    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py

    - name: 提交状态变更
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add last_known_versions.json
        git diff --quiet && git diff --staged --quiet || git commit -m "更新游戏状态 [skip ci]"
        git push
