name: Steam游戏监控

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: pip install feedparser requests python-dateutil

    - name: 初始化状态
      run: |
        if [ ! -f last_known_versions.json ]; then
          echo "{}" > last_known_versions.json
        fi

    - name: 运行监控
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python steam_monitor.py

    - name: 保存状态
      uses: actions/cache@v3
      with:
        path: last_known_versions.json
        key: steam-state-${{ github.run_id }}
